// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QAB {
    
    public class FIRST {
        public const string BUNDLENAME = "first";
        public const string ASD = "asd";
    }
    public class FIRST3 {
        public const string BUNDLENAME = "first2/first3";
        public const string ASD = "asd";
    }
    public class FIRST4 {
        public const string BUNDLENAME = "first2/first4";
        public const string ASD = "asd";
    }
    public class FIRST5 {
        public const string BUNDLENAME = "first2/first5";
        public const string ASD = "asd";
    }
    public class FIRST6 {
        public const string BUNDLENAME = "first2/first6";
        public const string ASD = "asd";
    }
    public class GAMELOGIC {
        public const string BUNDLENAME = "gamelogic";
        public const string BGLAYER = "bglayer";
        public const string DEATHZONE = "deathzone";
        public const string LANDEFFECT = "landeffect";
        public const string MAGNETITELAYER = "magnetitelayer";
        public const string PLAYER = "player";
        public const string RAINPREFAB2D = "rainprefab2d";
        public const string STAGELAYER = "stagelayer";
        public const string SUN = "sun";
    }
    public class SOUND {
        public const string BUNDLENAME = "sound";
        public const string BOSSSHAKE = "bossshake";
        public const string BTN = "btn";
        public const string COIN = "coin";
        public const string COIN2 = "coin2";
        public const string DEATH = "death";
        public const string ENEMYDEATH1 = "enemydeath1";
        public const string ENEMYDEATH2 = "enemydeath2";
        public const string FIRE = "fire";
        public const string FOREST = "forest";
        public const string FRUIT = "fruit";
        public const string GAME = "game";
        public const string HERO_HURT = "hero_hurt";
        public const string HOME = "home";
        public const string JUMP = "jump";
        public const string JUMP1 = "jump1";
        public const string JUMP2 = "jump2";
        public const string PROP_BIG = "prop_big";
        public const string SELECT = "select";
        public const string SHAKE = "shake";
        public const string UNUSE1 = "unuse1";
        public const string UNUSE2 = "unuse2";
        public const string UNUSE3 = "unuse3";
        public const string UNUSE4 = "unuse4";
        public const string UNUSE5 = "unuse5";
    }
    public class STAGESPAWNPOOLS {
        public const string BUNDLENAME = "stagespawnpools";
        public const string STAGE1SPAWNPOOL = "stage1spawnpool";
        public const string STAGE2SPAWNPOOL = "stage2spawnpool";
        public const string STAGE3SPAWNPOOL = "stage3spawnpool";
        public const string STAGE4SPAWNPOOL = "stage4spawnpool";
    }
    public class TESTAB {
        public const string BUNDLENAME = "testab";
        public const string CANVAS = "canvas";
        public const string EVENTSYSTEM = "eventsystem";
    }
    public class UIPREFAB {
        public const string BUNDLENAME = "uiprefab";
        public const string UIBOTTOMFRAME = "uibottomframe";
        public const string UICOMMONBG = "uicommonbg";
        public const string UIGAMELAYER = "uigamelayer";
        public const string UIGOLDLABEL = "uigoldlabel";
        public const string UIHELPLAYER = "uihelplayer";
        public const string UIHOMEBG = "uihomebg";
        public const string UIHOMELAYER = "uihomelayer";
        public const string UIPAUSELAYER = "uipauselayer";
        public const string UISETTINGLAYER = "uisettinglayer";
        public const string UISHOPLAYER = "uishoplayer";
        public const string UITOPFRAME = "uitopframe";
    }
}
