// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QAssetBundle {
    
    public class UIPREFAB {
        public const string BUNDLE_NAME = "UIPREFAB";
        public const string UIEDITPANEL = "UIEDITPANEL";
        public const string UIEXAMPLE4ABOUTPAGE = "UIEXAMPLE4ABOUTPAGE";
        public const string UIEXAMPLE4DIALOG = "UIEXAMPLE4DIALOG";
        public const string UIEXAMPLE4GAMEPAGE = "UIEXAMPLE4GAMEPAGE";
        public const string UIEXAMPLE4MAINPAGE = "UIEXAMPLE4MAINPAGE";
        public const string UIEXAMPLE5ABOUTPAGE = "UIEXAMPLE5ABOUTPAGE";
        public const string UIEXAMPLE5DIALOG = "UIEXAMPLE5DIALOG";
        public const string UIEXAMPLE5GAMEPAGE = "UIEXAMPLE5GAMEPAGE";
        public const string UIEXAMPLE5MAINPAGE = "UIEXAMPLE5MAINPAGE";
        public const string UIHOMEPAGE = "UIHOMEPAGE";
        public const string UITODOLISTPAGE = "UITODOLISTPAGE";
    }
}
