// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QFramework {
    
    /// <summary>
    /// AssetBundle相关的路径
    /// </summary>
    public class ABEditorPathConfig {
        private const string m_AssetBundleOutputPath = "AssetBundles";
        private const string m_ABGeneratePathiOS = "AssetBundles/iOS/qframework";
        private const string m_ABGeneratePathAndroid = "AssetBundles/Android/qframework";
        private const string m_ABGeneratePathOSX = "AssetBundles/OSX/qframework";
        private const string m_ABCodeGeneratePath = "QFrameworkData/Res";
        /// <summary>
        /// 工程资源存放路径
        /// </summary>
        public static string AssetBundleOutputPath {
            get {
                return QFramework.Libs.IOUtils.CreateDirIfNotExists (UnityEngine.Application.streamingAssetsPath + "/" + m_AssetBundleOutputPath);
            }
        }
        /// <summary>
        /// iOS平台 AB资源生成路径
        /// </summary>
        public static string ABGeneratePathiOS {
            get {
                return QFramework.Libs.IOUtils.CreateDirIfNotExists (UnityEngine.Application.streamingAssetsPath + "/" + m_ABGeneratePathiOS);
            }
        }
        /// <summary>
        /// Android平台 AB资源生成路径
        /// </summary>
        public static string ABGeneratePathAndroid {
            get {
                return QFramework.Libs.IOUtils.CreateDirIfNotExists (UnityEngine.Application.streamingAssetsPath + "/" + m_ABGeneratePathAndroid);
            }
        }
        /// <summary>
        /// OSX平台 AB资源生成路径
        /// </summary>
        public static string ABGeneratePathOSX {
            get {
                return QFramework.Libs.IOUtils.CreateDirIfNotExists (UnityEngine.Application.streamingAssetsPath + "/" + m_ABGeneratePathOSX);
            }
        }
        /// <summary>
        /// AB代码生成的路径
        /// </summary>
        public static string ABCodeGeneratePath {
            get {
                return QFramework.Libs.IOUtils.CreateDirIfNotExists (UnityEngine.Application.dataPath + "/" + m_ABCodeGeneratePath);
            }
        }
    }
}
