// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QFramework {
    
    /// <summary>
    /// AssetBundle相关的路径
    /// </summary>
    public class ABEditorPathConfig {
        private const string m_ScriptGeneratorPath = "_Script/UI";
        private const string m_ABGeneratePathiOS = "StreamingAssets/AssetBundles/iOS/putaogame/";
        /// <summary>
        /// 工程资源存放路径
        /// </summary>
        public static string ScriptGeneratorPath {
            get {
                return QFramework.Libs.IOUtils.CreateDirIfNotExists (UnityEngine.Application.dataPath + "/" + m_ScriptGeneratorPath);
            }
        }
        /// <summary>
        /// iOS平台 AB资源生成路径
        /// </summary>
        public static string ABGeneratePathiOS {
            get {
                return QFramework.Libs.IOUtils.CreateDirIfNotExists ("Assets/" + m_ABGeneratePathiOS);
            }
        }
    }
}
